FROM mysql:latest

ARG ROOT_PASSWORD=1234
ENV MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
# Var no terminal sempre maiuscula
COPY ./setup.sql /docker-entrypoint-initdb.d/setup.sql
EXPOSE 3306 
# Docker sempre roda na porta 3306
CMD [ "mysqld" ]